#!/usr/bin/env node
import * as esbuild from "esbuild";
import { createHash } from "crypto";
import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const isWatch = process.argv.includes("--watch");

const PATHS = {
  entry: path.join(__dirname, "src", "main.js"),
  bundle: path.join(__dirname, "public", "app.js"),
  templates: path.join(__dirname, "templates"),
  public: path.join(__dirname, "public"),
  releases: path.join(__dirname, "public", "releases"),
  releaseFile: path.join(__dirname, "public", "releases", "latest.txt"),
};

const HTML_TEMPLATES = [
  "app.html",
  "index.html",
  "private-source.html",
];

async function bundle() {
  const options = {
    entryPoints: [PATHS.entry],
    bundle: true,
    outfile: PATHS.bundle,
    format: "iife",
    platform: "browser",
    target: ["es2020"],
    minify: !isWatch,
    sourcemap: isWatch ? "inline" : false,
    legalComments: "none",
    define: {
      "process.env.NODE_ENV": JSON.stringify(isWatch ? "development" : "production"),
      "process.env.SWEEP_WORKER_SUBDOMAIN": JSON.stringify(
        process.env.SWEEP_WORKER_SUBDOMAIN || "smallcapstradingsystem"
      ),
      global: "globalThis",
    },
    inject: [path.join(__dirname, "src", "shim.js")],
    loader: {
      ".wasm": "binary",
    },
    alias: {
      stream: "stream-browserify",
      buffer: "buffer",
      crypto: "crypto-browserify",
    },
    logLevel: "info",
  };

  if (isWatch) {
    const ctx = await esbuild.context(options);
    await ctx.watch();
    console.log("Watching for changes...");
    return null;
  }
  await esbuild.build(options);
  console.log("  bundle written");
}

async function hashBundle(filePath) {
  const data = await fs.readFile(filePath);
  const sri = "sha384-" + createHash("sha384").update(data).digest("base64");
  const sha256 = createHash("sha256").update(data).digest("hex");
  return { sri, sha256, size: data.length };
}

async function renderTemplates(vars) {
  for (const file of HTML_TEMPLATES) {
    const src = path.join(PATHS.templates, file);
    const out = path.join(PATHS.public, file);
    try {
      let html = await fs.readFile(src, "utf8");
      for (const [k, v] of Object.entries(vars)) {
        html = html.split("{%" + k + "%}").join(v);
      }
      await fs.writeFile(out, html);
      console.log("  public/" + file + " written");
    } catch (e) {
      if (e.code !== "ENOENT") throw e;
      console.warn("  templates/" + file + " not found - skipped");
    }
  }
}

async function writeRelease(sri, sha256, size) {
  await fs.mkdir(PATHS.releases, { recursive: true });
  const date = new Date().toISOString();
  const content =
    "# Sweep app release\n" +
    "# Generated by build.js\n\n" +
    "date:         " + date + "\n" +
    "size_bytes:   " + size + "\n" +
    "size_kb:      " + (size / 1024).toFixed(1) + "\n" +
    "sha256_hex:   " + sha256 + "\n" +
    "sha384_sri:   " + sri + "\n\n" +
    "# Verify with:\n" +
    "#   curl -s https://YOUR_DOMAIN/app.js | openssl dgst -sha256\n";
  await fs.writeFile(PATHS.releaseFile, content);
  console.log("  public/releases/latest.txt written");
}

async function main() {
  console.log("Building...");
  const result = await bundle();
  if (result === null) return;

  const { sri, sha256, size } = await hashBundle(PATHS.bundle);
  console.log("  size:   " + (size / 1024).toFixed(1) + " KB");
  console.log("  sha256: " + sha256.slice(0, 16) + "...");

  const vars = {
    APP_JS_SRI: sri,
    APP_JS_SHA256: sha256,
    APP_JS_SIZE: size.toString(),
    APP_JS_SIZE_KB: (size / 1024).toFixed(1),
    BUILD_DATE: new Date().toISOString(),
  };

  await renderTemplates(vars);
  await writeRelease(sri, sha256, size);

  console.log("\nBuild complete.");
}

main().catch((err) => {
  console.error("Build failed:", err);
  process.exit(1);
});