#!/usr/bin/env node
import * as esbuild from "esbuild";
import { createHash } from "crypto";
import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const isWatch = process.argv.includes("--watch");

const PATHS = {
  entry: path.join(__dirname, "src", "main.js"),
  adminEntry: path.join(__dirname, "src", "admin", "admin.js"),
  bundle: path.join(__dirname, "public", "app.js"),
  adminBundle: path.join(__dirname, "public", "admin.js"),
  templates: path.join(__dirname, "templates"),
  public: path.join(__dirname, "public"),
  releases: path.join(__dirname, "public", "releases"),
  releaseFile: path.join(__dirname, "public", "releases", "latest.txt"),
};

const HTML_TEMPLATES = [
  "app.html",
  "index.html",
  "private-source.html",
];

// Shared options for every bundle. Each bundle overrides `entryPoints`
// and `outfile`.
function baseOptions() {
  return {
    bundle: true,
    format: "iife",
    platform: "browser",
    target: ["es2020"],
    minify: !isWatch,
    sourcemap: isWatch ? "inline" : false,
    legalComments: "none",
    define: {
      "process.env.NODE_ENV": JSON.stringify(isWatch ? "development" : "production"),
      "process.env.SWEEP_WORKER_SUBDOMAIN": JSON.stringify(
        process.env.SWEEP_WORKER_SUBDOMAIN || "smallcapstradingsystem"
      ),
      global: "globalThis",
    },
    inject: [path.join(__dirname, "src", "shim.js")],
    loader: {
      ".wasm": "binary",
    },
    alias: {
      stream: "stream-browserify",
      buffer: "buffer",
      crypto: "crypto-browserify",
    },
    logLevel: "info",
  };
}

async function bundle() {
  const common = baseOptions();

  const appOptions = { ...common, entryPoints: [PATHS.entry], outfile: PATHS.bundle };
  const adminOptions = { ...common, entryPoints: [PATHS.adminEntry], outfile: PATHS.adminBundle };

  if (isWatch) {
    const appCtx = await esbuild.context(appOptions);
    await appCtx.watch();

    // The admin bundle is optional — if the admin entry hasn't been
    // created yet, skip it rather than failing the whole watch.
    try {
      await fs.access(PATHS.adminEntry);
      const adminCtx = await esbuild.context(adminOptions);
      await adminCtx.watch();
    } catch {
      console.warn("  src/admin/admin.js not found — skipping admin bundle");
    }

    console.log("Watching for changes...");
    return null;
  }

  await esbuild.build(appOptions);
  console.log("  app.js bundle written");

  // Admin bundle is optional. If it fails to build (e.g. file missing),
  // warn and continue — the app itself is the primary artifact.
  try {
    await fs.access(PATHS.adminEntry);
    await esbuild.build(adminOptions);
    console.log("  admin.js bundle written");
  } catch (e) {
    if (e.code === "ENOENT") {
      console.warn("  src/admin/admin.js not found — skipping admin bundle");
    } else {
      throw e;
    }
  }
}

async function hashBundle(filePath) {
  const data = await fs.readFile(filePath);
  const sri = "sha384-" + createHash("sha384").update(data).digest("base64");
  const sha256 = createHash("sha256").update(data).digest("hex");
  return { sri, sha256, size: data.length };
}

async function renderTemplates(vars) {
  for (const file of HTML_TEMPLATES) {
    const src = path.join(PATHS.templates, file);
    const out = path.join(PATHS.public, file);
    try {
      let html = await fs.readFile(src, "utf8");
      for (const [k, v] of Object.entries(vars)) {
        html = html.split("{%" + k + "%}").join(v);
      }
      await fs.writeFile(out, html);
      console.log("  public/" + file + " written");
    } catch (e) {
      if (e.code !== "ENOENT") throw e;
      console.warn("  templates/" + file + " not found - skipped");
    }
  }
}

async function writeRelease(sri, sha256, size) {
  await fs.mkdir(PATHS.releases, { recursive: true });
  const date = new Date().toISOString();
  const content =
    "# Sweep app release\n" +
    "# Generated by build.js\n\n" +
    "date:         " + date + "\n" +
    "size_bytes:   " + size + "\n" +
    "size_kb:      " + (size / 1024).toFixed(1) + "\n" +
    "sha256_hex:   " + sha256 + "\n" +
    "sha384_sri:   " + sri + "\n\n" +
    "# Verify with:\n" +
    "#   curl -s https://YOUR_DOMAIN/app.js | openssl dgst -sha256\n";
  await fs.writeFile(PATHS.releaseFile, content);
  console.log("  public/releases/latest.txt written");
}

async function main() {
  console.log("Building...");
  const result = await bundle();
  if (result === null) return;

  const { sri, sha256, size } = await hashBundle(PATHS.bundle);
  console.log("  app.js size:   " + (size / 1024).toFixed(1) + " KB");
  console.log("  app.js sha256: " + sha256.slice(0, 16) + "...");

  const vars = {
    APP_JS_SRI: sri,
    APP_JS_SHA256: sha256,
    APP_JS_SIZE: size.toString(),
    APP_JS_SIZE_KB: (size / 1024).toFixed(1),
    BUILD_DATE: new Date().toISOString(),
    // Same source as src/env.js — the esbuild `define` above and this
    // template substitution both read the same env var, so the worker
    // URL in the static pages can never drift from the one baked into
    // app.js.
    WORKER_SUBDOMAIN:
      process.env.SWEEP_WORKER_SUBDOMAIN || "smallcapstradingsystem",
  };

  await renderTemplates(vars);
  await writeRelease(sri, sha256, size);

  console.log("\nBuild complete.");
}

main().catch((err) => {
  console.error("Build failed:", err);
  process.exit(1);
});